# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuckarooTransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('190', 'Success'), ('490', 'Failed'), ('491', 'Validation Failure'), ('492', 'Technical Failure'), ('690', 'Rejected'), ('790', 'Pending input'), ('791', 'Pending processing'), ('792', 'Awaiting consumer'), ('793', 'On Hold'), ('890', 'Cancelled By User'), ('891', 'Cancelled By Merchant')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('ideal', 'iDeal'), ('creditcard', 'Creditcard')], max_length=300)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('card', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
