# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckaroo', '0002_auto_20160809_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bank',
            new_name='bank_code',
        ),
    ]
