# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckaroo', '0003_auto_20160810_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
