# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckaroo', '0006_transaction_last_push'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buckaroo_push',
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
